name: 01 - Building Blocks

on:
  - workflow_dispatch

jobs:

  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
      - name: Say hello by workflow-dispatch
        run: echo "Hello world by workflow dispatch"
