name: 02 - Workflow Events

on:
  #push:
  #schedule:
  #  - cron: '*/5 * * * *'
  #pull_request:
  workflow_dispatch:


jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "i hv triggered this action by event type ${{ github.event_name }}"

