name: 04 - Using Actions

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/workflows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List the files and directory
        run: |
          echo "Now we are checkinto the git repo"
          echo "By using actions"
          ls -a
      - name: List the files under .github/workflows
        run: |
          echo "Now we are printing files under workflows directory"
          ls
        #working-directory: .github/workflows or we can define the working directory @ job level also

 