name: 08 - Using Expressions

run-name: Context | DEBUG - ${{ inputs.debug && 'ON' || 'OFF'}}


on:
  #push:
  workflow_dispatch:
   inputs:
     debug:
       type: boolean
       default: FALSE

#env:
  #MY_VAR: ${{ var.MY_VALUE || 'DEFAULT' }}  #Means if the value fo the variable MY_VAR is not available then it's value will or DEFAULT


jobs:

  echo:
    runs-on: ubuntu-latest

    steps:
      - name: '[debug] Print the start-up data'
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner: ${{ runner.os }}"

      - name: '[debug] Print when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
        run: |
          echo "I was triggered from main"

      - name: Greeting
        run: |
          echo "Hello, world"
