name: 08 - Using EVariables

run-name: Variables

on:
  #push:
  workflow_dispatch:
   inputs:
     debug:
       type: boolean
       default: false

env:
  WORKFLOW_VAR: 'I am workflow env var'
  OVERWRITTEN: 'I will be overwritten'

jobs:

  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am job env var'
      OVERWRITTEN: 'I will be overwritten at the job level'
    steps:
      - name: Print Env variables
        env:
          STEP_VAR: 'I am a step env var'
          STEP_VAR2: 'I am another env var'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var: ${{ env.STEP_VAR2 }}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"

      - name: Overwrite the job variable
        env:
          OVERWRITTEN: 'I am been overwritten at the step level'
        run: |
          echo "OVERWRITTEN"

      - name: Actual workflow values
        run: |
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"

  echo-repo-env-variables:
    runs-on: ubuntu-latest
  
    steps:
      - name: Print Repo Env variables
        run: |
          echo "Repo env var: ${{ vars.REPO_VAR }}"
          echo "Repo over env var: ${{ vars.REPO_OVER_VAR }}"

  echo-env-variables1:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Repo Env variables
        run: |
          echo "Prod env target_var: ${{ vars.TARGET_VAR }}"

  echo-env-variables2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print Repo Env variables
        run: |
          echo "Prod env target_var: ${{ vars.TARGET_VAR }}"


      #Here we created 2 env prod and staging with common variable TARGET_VAR, so when we set ,
      #environment: prod it will print the TARGET_VAR value of prod environment
      #environment: staging it will print the TARGET_VAR value of staging environment
