name: 14 - 03 - Using Matrix

on:
  workflow_dispatch:

jobs:

  backward-compatibility:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include:
          - color: red
            opacity: 100       #It will hv opacity value 75 for color with red
          - shape: circle
            opacity: 75      #It will hv opacity value 100 for shape with circle
          - color: red
            shape: triangle
            opacity: 50       #It will hv opacity value 50 for shape with triangle
          - opacity: 50        #since it was defined at end it will fix all opacity value to 50 
    steps:
      - name: Dummy steps
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
 
