name: 18 - 02 - Using Reusable workflow trigger

#This workflow is not triggered, this workflow is called in another workflow

on:
  workflow_dispatch:

jobs:
  some-job:
    uses: .github/workflows/18-01-using-reusable.yaml
    with:
      target-directory: dummy-dir

  print-outputs:
    runs-on: ubuntu-latest
    needs: some-job
    steps:
      - name: Print outputs
        run: |
          echo "Build status ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"
        
