name: 18 - 01 - Using Reusable workflow trigger from diff private repo with access token

#This is the workflow created on diff private repo, 
#that needs to be called from another caller repo
on:
  workflow_dispatch:

jobs:
  some-job:
    uses: ./.github/workflows/17-01-using-reusable.yaml
    with:
      target-directory: dummy-dir

  print-outputs:
    runs-on: ubuntu-latest
    needs: some-job
    steps:
      - name: Print outputs
        run: |
          echo "Build status ${{ needs.some-job.outputs.build-status }}"
          echo "URL: ${{ needs.some-job.outputs.url }}"

  #e2e-tests:
   # uses: JEEVANBG/Jenkinsfile/.github/workflows/18-02-using-reusable-workflow-from-diff-repo.yaml@main 
    #secrets:
     #   access-token: ${{ secrets.GH_TOKEN }}