name: 18 - 02 - Using Reusable workflow trigger from diff private repo with access token

#This workflow is not triggered, this workflow is called in another workflow

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  E2E-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: JEEVANBG/Jenkinsfile.git
          ref: main
      - name: Check the build status
        run: |
          echo "Build status ${{ needs.some-job.outputs.build-status }}"
          echo "URL: ${{ needs.some-job.outputs.url }}"
      - name: List the files n folders
        run: ll        
